language: php

php:
  - 7.1
  - 7.2
  - 7.3

env:
  global:
    - COMPOSER_FLAGS=""
  matrix:
    - LARAVEL=5.6.*
    - LARAVEL=5.7.*
    - LARAVEL=5.8.*
    - COMPOSER_FLAGS="--prefer-lowest" LARAVEL=5.6.*
    - COMPOSER_FLAGS="--prefer-lowest" LARAVEL=5.7.*
    - COMPOSER_FLAGS="--prefer-lowest" LARAVEL=5.8.*


before_install:
  - travis_retry composer self-update


before_script:
  - travis_retry composer require "laravel/framework=${LARAVEL}" --prefer-source --no-interaction --no-suggest
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - ./vendor/bin/phpunit
